"""composite indexes for hot paths

Revision ID: 360966087c24
Revises: 946b1470ebed
Create Date: 2026-06-24 13:26:44.663584
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '360966087c24'
down_revision: Union[str, None] = '946b1470ebed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_lesson_user_learned', 'lesson_events', ['user_id', 'learned_at'], unique=False)
    op.create_index('ix_review_user_answered', 'review_events', ['user_id', 'answered_at'], unique=False)
    op.create_index('ix_review_user_item', 'review_events', ['user_id', 'item_id'], unique=False)
    op.create_index('ix_state_user_available', 'user_item_state', ['user_id', 'available_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_state_user_available', table_name='user_item_state')
    op.drop_index('ix_review_user_item', table_name='review_events')
    op.drop_index('ix_review_user_answered', table_name='review_events')
    op.drop_index('ix_lesson_user_learned', table_name='lesson_events')
    # ### end Alembic commands ###
