"""user tos_accepted_at

Revision ID: 5c855cc222d4
Revises: 3284f0181e9e
Create Date: 2026-07-06 12:02:05.721555
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5c855cc222d4'
down_revision: Union[str, None] = '3284f0181e9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tos_accepted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tos_accepted_at')
    # ### end Alembic commands ###
