"""initial schema

Revision ID: 946b1470ebed
Revises: 
Create Date: 2026-06-23 02:23:32.741590
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '946b1470ebed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('license', sa.String(length=64), nullable=True),
    sa.Column('attribution', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_assets_key'), 'audio_assets', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('auth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_tokens_token_hash'), 'auth_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_tokens_type'), 'auth_tokens', ['type'], unique=False)
    op.create_index(op.f('ix_auth_tokens_user_id'), 'auth_tokens', ['user_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('lemma', sa.String(length=128), nullable=False),
    sa.Column('stressed_form', sa.String(length=128), nullable=False),
    sa.Column('translation_primary', sa.String(length=255), nullable=False),
    sa.Column('translations', sa.JSON(), nullable=False),
    sa.Column('part_of_speech', sa.String(length=32), nullable=True),
    sa.Column('gender', sa.String(length=8), nullable=True),
    sa.Column('aspect', sa.String(length=16), nullable=True),
    sa.Column('aspect_pair_id', sa.Integer(), nullable=True),
    sa.Column('ipa', sa.String(length=128), nullable=True),
    sa.Column('audio_url', sa.String(length=512), nullable=True),
    sa.Column('frequency_rank', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aspect_pair_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_lemma'), 'items', ['lemma'], unique=False)
    op.create_index(op.f('ix_items_level'), 'items', ['level'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('keys', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('plan', sa.String(length=16), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=64), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=64), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    op.create_table('example_sentences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('ru_text', sa.Text(), nullable=False),
    sa.Column('en_text', sa.Text(), nullable=False),
    sa.Column('audio_url', sa.String(length=512), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('license', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_example_sentences_item_id'), 'example_sentences', ['item_id'], unique=False)
    op.create_table('lesson_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('learned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_events_item_id'), 'lesson_events', ['item_id'], unique=False)
    op.create_index(op.f('ix_lesson_events_user_id'), 'lesson_events', ['user_id'], unique=False)
    op.create_table('mnemonics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meaning_mnemonic', sa.Text(), nullable=True),
    sa.Column('reading_mnemonic', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'user_id', name='uq_mnemonic_item_user')
    )
    op.create_index(op.f('ix_mnemonics_item_id'), 'mnemonics', ['item_id'], unique=False)
    op.create_index(op.f('ix_mnemonics_user_id'), 'mnemonics', ['user_id'], unique=False)
    op.create_table('review_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=16), nullable=False),
    sa.Column('client_event_id', sa.String(length=64), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('was_override', sa.Boolean(), nullable=False),
    sa.Column('srs_before', sa.Integer(), nullable=True),
    sa.Column('srs_after', sa.Integer(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_event_id', name='uq_review_client_id')
    )
    op.create_index(op.f('ix_review_events_item_id'), 'review_events', ['item_id'], unique=False)
    op.create_index(op.f('ix_review_events_user_id'), 'review_events', ['user_id'], unique=False)
    op.create_table('user_item_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('srs_stage', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('passed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('burned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('incorrect_count', sa.Integer(), nullable=False),
    sa.Column('correct_streak', sa.Integer(), nullable=False),
    sa.Column('guru_to_apprentice_demotions', sa.Integer(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('leech_score', sa.Float(), nullable=False),
    sa.Column('is_leech', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_id', name='uq_state_user_item')
    )
    op.create_index(op.f('ix_user_item_state_available_at'), 'user_item_state', ['available_at'], unique=False)
    op.create_index(op.f('ix_user_item_state_item_id'), 'user_item_state', ['item_id'], unique=False)
    op.create_index(op.f('ix_user_item_state_user_id'), 'user_item_state', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_item_state_user_id'), table_name='user_item_state')
    op.drop_index(op.f('ix_user_item_state_item_id'), table_name='user_item_state')
    op.drop_index(op.f('ix_user_item_state_available_at'), table_name='user_item_state')
    op.drop_table('user_item_state')
    op.drop_index(op.f('ix_review_events_user_id'), table_name='review_events')
    op.drop_index(op.f('ix_review_events_item_id'), table_name='review_events')
    op.drop_table('review_events')
    op.drop_index(op.f('ix_mnemonics_user_id'), table_name='mnemonics')
    op.drop_index(op.f('ix_mnemonics_item_id'), table_name='mnemonics')
    op.drop_table('mnemonics')
    op.drop_index(op.f('ix_lesson_events_user_id'), table_name='lesson_events')
    op.drop_index(op.f('ix_lesson_events_item_id'), table_name='lesson_events')
    op.drop_table('lesson_events')
    op.drop_index(op.f('ix_example_sentences_item_id'), table_name='example_sentences')
    op.drop_table('example_sentences')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_items_level'), table_name='items')
    op.drop_index(op.f('ix_items_lemma'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_auth_tokens_user_id'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_type'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_token_hash'), table_name='auth_tokens')
    op.drop_table('auth_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_audio_assets_key'), table_name='audio_assets')
    op.drop_table('audio_assets')
    # ### end Alembic commands ###
