"""user synonyms table

Revision ID: ac23b7f69bc3
Revises: 360966087c24
Create Date: 2026-06-26 03:18:07.197908
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ac23b7f69bc3'
down_revision: Union[str, None] = '360966087c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_synonyms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_id', 'text', name='uq_synonym_user_item_text')
    )
    op.create_index('ix_synonym_user_item', 'user_synonyms', ['user_id', 'item_id'], unique=False)
    op.create_index(op.f('ix_user_synonyms_item_id'), 'user_synonyms', ['item_id'], unique=False)
    op.create_index(op.f('ix_user_synonyms_user_id'), 'user_synonyms', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_synonyms_user_id'), table_name='user_synonyms')
    op.drop_index(op.f('ix_user_synonyms_item_id'), table_name='user_synonyms')
    op.drop_index('ix_synonym_user_item', table_name='user_synonyms')
    op.drop_table('user_synonyms')
    # ### end Alembic commands ###
